import { IDashboardState, IRouterState } from '../../types';
import * as selectors from './dashboard.selectors';

describe('DashboardSelector', () => {
  it('testing selectLastUpdated positions selector', () => {
    const lastUpdated = selectors.selectLastUpdated({
      router: {
        state: {
          root: {
            params: {},
            data: {},
            url: [],
            outlet: 'primary',
            routeConfig: null,
            queryParams: {},
            firstChild: null,
            children: [],
          },
          url: '/dashboard/position',
        },
        navigationId: 6,
      },
      dashboard: {
        risk: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
            collateralId: {
              type: 'string',
              editable: false,
              touched: false,
              value: '2',
              error: null,
              async: false,
              validatable: true,
              validated: true,
              validating: false,
            },
          },
          summary: {
            participantId: '100',
            collateralId: '200',
            settlementBalance: 100,
            netDepitCap: 200,
            collateralMonitor: 300,
            sppNetActivity: 400,
            netDirection: 'D',
            valueAtRisk: 100,
          },
          lastUpdated: new Date('12/10/2020'),
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
        },
        position: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
            cusip: {
              type: 'string',
              editable: true,
              touched: false,
              value: '3',
              error: null,
              async: false,
              validatable: true,
              validated: true,
              validating: false,
            },
            date: {
              type: 'string',
              editable: true,
              touched: false,
              value: '12/10/2020',
              error: null,
              async: false,
              validatable: true,
              validated: true,
              validating: false,
            },
          },
          summary: {
            security: '1',
            ticker: '2',
            cusip: '3',
            netAdditions: 100,
            minimumAmount: 200,
            memoSegregation: 300,
            totalFreeExcess: 400,
            pledged: 500,
            totalPositions: 600,
          },
          dialog: {
            cusip: false,
          },
          lastUpdated: new Date('11/10/2020'),
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
        },
        cca: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
            settlementDate: {
              type: 'string',
              editable: true,
              touched: false,
              value: ['12/12/2020', '12/14/2020'],
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
          },
          summary: {
            participantId: '111',
            adjustments: [
              {
                ccaId: '123',
                settlementDate: '12/12/2020',
                debitCredit: 'Debit',
                netCCAAmount: 1231.12,
                settlementStatus: 'OPEN',
              },
              {
                ccaId: '234',
                settlementDate: '12/16/2020',
                debitCredit: 'Credit',
                netCCAAmount: 2345.34,
                settlementStatus: 'COMPLETE',
              },
            ],
          },
          detail: {
            ccaId: null,
            cusip: '',
            debits: [],
            credits: [],
          },
          lastUpdated: null,
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
        },
        obligation: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
          },
          lastUpdated: new Date('10/10/2020'),
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
          selection: {
            itemId: '2',
            pendingId: '3',
            transactions: [
              {
                transactionId: '1',
                cusip: '2',
                contra: 100,
                deliverReceiver: '3',
                quantity: 200,
                tradeAmount: 300,
                status: '4',
                activity: '5',
                source: '6',
                reason: '7',
              },
            ],
            trades: [
              {
                tradeId: '1',
                ticker: '2',
                cusip: '3',
                buySell: '4',
                quantity: 100,
                tradePrice: 200,
                tradeAmount: 300,
                settlementDate: '12/10/2020',
                market: 'AAPL',
                tradeDate: '2020-12-01',
              },
            ],
          },
          summary: {
            cusip: '100',
            sortBy: undefined,
            longs: [
              {
                netObligationId: '',
                securityName: '',
                cusip: '',
                ticker: '',
                isin: '',
                netQuantity: 100,
                netTradeAmount: 200,
                settlementValue: 300,
                settlementDate: '',
                closePrice: 400,
                settlementStatus: '',
              },
            ],
            shorts: [
              {
                netObligationId: '',
                securityName: '',
                cusip: '',
                ticker: '',
                isin: '',
                netQuantity: 100,
                netTradeAmount: 200,
                settlementValue: 300,
                settlementDate: '',
                closePrice: 400,
                settlementStatus: '',
              },
            ],
            closed: [
              {
                netObligationId: '',
                securityName: '',
                cusip: '',
                ticker: '',
                isin: '',
                netQuantity: 100,
                netTradeAmount: 200,
                settlementValue: 300,
                settlementDate: '',
                closePrice: 400,
                settlementStatus: '',
              },
            ],
          },
          dialog: {
            cusip: false,
          },
        },
      },
    } as { dashboard: IDashboardState });
    expect(lastUpdated).toEqual(new Date('11/10/2020'));
  });

  it('testing selectLastUpdated obligations selector', () => {
    const lastUpdated = selectors.selectLastUpdated({
      router: {
        state: {
          root: {
            params: {},
            data: {},
            url: [],
            outlet: 'primary',
            routeConfig: null,
            queryParams: {},
            firstChild: null,
            children: [],
          },
          url: '/dashboard/obligations',
        },
        navigationId: 6,
      },
      dashboard: {
        risk: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
            collateralId: {
              type: 'string',
              editable: false,
              touched: false,
              value: '2',
              error: null,
              async: false,
              validatable: true,
              validated: true,
              validating: false,
            },
          },
          summary: {
            participantId: '100',
            collateralId: '200',
            settlementBalance: 100,
            netDepitCap: 200,
            collateralMonitor: 300,
            sppNetActivity: 400,
            netDirection: 'D',
            valueAtRisk: 100,
          },
          lastUpdated: new Date('12/10/2020'),
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
        },
        position: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
            cusip: {
              type: 'string',
              editable: true,
              touched: false,
              value: '3',
              error: null,
              async: false,
              validatable: true,
              validated: true,
              validating: false,
            },
            date: {
              type: 'string',
              editable: true,
              touched: false,
              value: '12/10/2020',
              error: null,
              async: false,
              validatable: true,
              validated: true,
              validating: false,
            },
          },
          summary: {
            security: '1',
            ticker: '2',
            cusip: '3',
            netAdditions: 100,
            minimumAmount: 200,
            memoSegregation: 300,
            totalFreeExcess: 400,
            pledged: 500,
            totalPositions: 600,
          },
          dialog: {
            cusip: false,
          },
          lastUpdated: new Date('11/10/2020'),
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
        },
        cca: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
            settlementDate: {
              type: 'string',
              editable: true,
              touched: false,
              value: ['12/12/2020', '12/14/2020'],
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
          },
          summary: {
            participantId: '111',
            adjustments: [
              {
                ccaId: '123',
                settlementDate: '12/12/2020',
                debitCredit: 'Debit',
                netCCAAmount: 1231.12,
                settlementStatus: 'OPEN',
              },
              {
                ccaId: '234',
                settlementDate: '12/16/2020',
                debitCredit: 'Credit',
                netCCAAmount: 2345.34,
                settlementStatus: 'COMPLETE',
              },
            ],
          },
          detail: {
            ccaId: null,
            cusip: '',
            debits: [],
            credits: [],
          },
          lastUpdated: null,
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
        },
        obligation: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
          },
          lastUpdated: new Date('10/10/2020'),
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
          selection: {
            itemId: '2',
            pendingId: '3',
            transactions: [
              {
                transactionId: '1',
                cusip: '2',
                contra: 100,
                deliverReceiver: '3',
                quantity: 200,
                tradeAmount: 300,
                status: '4',
                activity: '5',
                source: '6',
                reason: '7',
              },
            ],
            trades: [
              {
                tradeId: '1',
                ticker: '2',
                cusip: '3',
                buySell: '4',
                quantity: 100,
                tradePrice: 200,
                tradeAmount: 300,
                settlementDate: '12/10/2020',
                market: 'AAPL',
                tradeDate: '2020-12-01',
              },
            ],
          },
          summary: {
            cusip: '100',
            sortBy: undefined,
            longs: [
              {
                netObligationId: '',
                securityName: '',
                cusip: '',
                ticker: '',
                isin: '',
                netQuantity: 100,
                netTradeAmount: 200,
                settlementValue: 300,
                settlementDate: '',
                closePrice: 400,
                settlementStatus: '',
              },
            ],
            shorts: [
              {
                netObligationId: '',
                securityName: '',
                cusip: '',
                ticker: '',
                isin: '',
                netQuantity: 100,
                netTradeAmount: 200,
                settlementValue: 300,
                settlementDate: '',
                closePrice: 400,
                settlementStatus: '',
              },
            ],
            closed: [
              {
                netObligationId: '',
                securityName: '',
                cusip: '',
                ticker: '',
                isin: '',
                netQuantity: 100,
                netTradeAmount: 200,
                settlementValue: 300,
                settlementDate: '',
                closePrice: 400,
                settlementStatus: '',
              },
            ],
          },
          dialog: {
            cusip: false,
          },
        },
      },
    } as { dashboard: IDashboardState });
    expect(lastUpdated).toEqual(new Date('10/10/2020'));
  });

  it('testing selectLastUpdated risk-mannagemet selector', () => {
    const lastUpdated = selectors.selectLastUpdated({
      router: {
        state: {
          root: {
            params: {},
            data: {},
            url: [],
            outlet: 'primary',
            routeConfig: null,
            queryParams: {},
            firstChild: null,
            children: [],
          },
          url: '/dashboard/risk-management',
        },
        navigationId: 6,
      },
      dashboard: {
        risk: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
            collateralId: {
              type: 'string',
              editable: false,
              touched: false,
              value: '2',
              error: null,
              async: false,
              validatable: true,
              validated: true,
              validating: false,
            },
          },
          summary: {
            participantId: '100',
            collateralId: '200',
            settlementBalance: 100,
            netDepitCap: 200,
            collateralMonitor: 300,
            sppNetActivity: 400,
            netDirection: 'D',
            valueAtRisk: 100,
          },
          lastUpdated: new Date('12/10/2020'),
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
        },
        position: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
            cusip: {
              type: 'string',
              editable: true,
              touched: false,
              value: '3',
              error: null,
              async: false,
              validatable: true,
              validated: true,
              validating: false,
            },
            date: {
              type: 'string',
              editable: true,
              touched: false,
              value: '12/10/2020',
              error: null,
              async: false,
              validatable: true,
              validated: true,
              validating: false,
            },
          },
          summary: {
            security: '1',
            ticker: '2',
            cusip: '3',
            netAdditions: 100,
            minimumAmount: 200,
            memoSegregation: 300,
            totalFreeExcess: 400,
            pledged: 500,
            totalPositions: 600,
          },
          dialog: {
            cusip: false,
          },
          lastUpdated: new Date('11/10/2020'),
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
        },
        cca: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
            settlementDate: {
              type: 'string',
              editable: true,
              touched: false,
              value: ['12/12/2020', '12/14/2020'],
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
          },
          summary: {
            participantId: '111',
            adjustments: [
              {
                ccaId: '123',
                settlementDate: '12/12/2020',
                debitCredit: 'Debit',
                netCCAAmount: 1231.12,
                settlementStatus: 'OPEN',
              },
              {
                ccaId: '234',
                settlementDate: '12/16/2020',
                debitCredit: 'Credit',
                netCCAAmount: 2345.34,
                settlementStatus: 'COMPLETE',
              },
            ],
          },
          detail: {
            ccaId: null,
            cusip: '',
            debits: [],
            credits: [],
          },
          lastUpdated: null,
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
        },
        obligation: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
          },
          lastUpdated: new Date('10/10/2020'),
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
          selection: {
            itemId: '2',
            pendingId: '3',
            transactions: [
              {
                transactionId: '1',
                cusip: '2',
                contra: 100,
                deliverReceiver: '3',
                quantity: 200,
                tradeAmount: 300,
                status: '4',
                activity: '5',
                source: '6',
                reason: '7',
              },
            ],
            trades: [
              {
                tradeId: '1',
                ticker: '2',
                cusip: '3',
                buySell: '4',
                quantity: 100,
                tradePrice: 200,
                tradeAmount: 300,
                settlementDate: '12/10/2020',
                market: 'AAPL',
                tradeDate: '2020-12-01',
              },
            ],
          },
          summary: {
            cusip: '100',
            sortBy: undefined,
            longs: [
              {
                netObligationId: '',
                securityName: '',
                cusip: '',
                ticker: '',
                isin: '',
                netQuantity: 100,
                netTradeAmount: 200,
                settlementValue: 300,
                settlementDate: '',
                closePrice: 400,
                settlementStatus: '',
              },
            ],
            shorts: [
              {
                netObligationId: '',
                securityName: '',
                cusip: '',
                ticker: '',
                isin: '',
                netQuantity: 100,
                netTradeAmount: 200,
                settlementValue: 300,
                settlementDate: '',
                closePrice: 400,
                settlementStatus: '',
              },
            ],
            closed: [
              {
                netObligationId: '',
                securityName: '',
                cusip: '',
                ticker: '',
                isin: '',
                netQuantity: 100,
                netTradeAmount: 200,
                settlementValue: 300,
                settlementDate: '',
                closePrice: 400,
                settlementStatus: '',
              },
            ],
          },
          dialog: {
            cusip: false,
          },
        },
      },
    } as { dashboard: IDashboardState });
    expect(lastUpdated).toEqual(new Date('12/10/2020'));
  });

  it('testing selectLastUpdated none selector', () => {
    const lastUpdated = selectors.selectLastUpdated({
      router: {
        state: {
          root: {
            params: {},
            data: {},
            url: [],
            outlet: 'primary',
            routeConfig: null,
            queryParams: {},
            firstChild: null,
            children: [],
          },
          url: '/dashboard/none',
        },
        navigationId: 6,
      },
      dashboard: {
        risk: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
            collateralId: {
              type: 'string',
              editable: false,
              touched: false,
              value: '2',
              error: null,
              async: false,
              validatable: true,
              validated: true,
              validating: false,
            },
          },
          summary: {
            participantId: '100',
            collateralId: '200',
            settlementBalance: 100,
            netDepitCap: 200,
            collateralMonitor: 300,
            sppNetActivity: 400,
            netDirection: 'D',
            valueAtRisk: 100,
          },
          lastUpdated: new Date('12/10/2020'),
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
        },
        position: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
            cusip: {
              type: 'string',
              editable: true,
              touched: false,
              value: '3',
              error: null,
              async: false,
              validatable: true,
              validated: true,
              validating: false,
            },
            date: {
              type: 'string',
              editable: true,
              touched: false,
              value: '12/10/2020',
              error: null,
              async: false,
              validatable: true,
              validated: true,
              validating: false,
            },
          },
          summary: {
            security: '1',
            ticker: '2',
            cusip: '3',
            netAdditions: 100,
            minimumAmount: 200,
            memoSegregation: 300,
            totalFreeExcess: 400,
            pledged: 500,
            totalPositions: 600,
          },
          dialog: {
            cusip: false,
            ticker: true,
          },
          lastUpdated: new Date('11/10/2020'),
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
        },
        cca: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
            settlementDate: {
              type: 'string',
              editable: true,
              touched: false,
              value: ['12/12/2020', '12/14/2020'],
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
          },
          summary: {
            participantId: '111',
            adjustments: [
              {
                ccaId: '123',
                settlementDate: '12/12/2020',
                debitCredit: 'Debit',
                netCCAAmount: 1231.12,
                settlementStatus: 'OPEN',
              },
              {
                ccaId: '234',
                settlementDate: '12/16/2020',
                debitCredit: 'Credit',
                netCCAAmount: 2345.34,
                settlementStatus: 'COMPLETE',
              },
            ],
          },
          detail: {
            ccaId: null,
            cusip: '',
            debits: [],
            credits: [],
          },
          lastUpdated: null,
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
        },
        obligation: {
          form: {
            participantId: {
              type: 'string',
              editable: true,
              touched: false,
              value: '1',
              error: null,
              async: true,
              validatable: true,
              validated: false,
              validating: false,
            },
          },
          lastUpdated: new Date('10/10/2020'),
          initialLoaded: null,
          pageLoaded: null,
          pageError: null,
          pageSuccess: null,
          selection: {
            itemId: '2',
            pendingId: '3',
            transactions: [
              {
                transactionId: '1',
                cusip: '2',
                contra: 100,
                deliverReceiver: '3',
                quantity: 200,
                tradeAmount: 300,
                status: '4',
                activity: '5',
                source: '6',
                reason: '7',
              },
            ],
            trades: [
              {
                tradeId: '1',
                ticker: '2',
                cusip: '3',
                buySell: '4',
                quantity: 100,
                tradePrice: 200,
                tradeAmount: 300,
                settlementDate: '12/10/2020',
                market: 'AAPL',
                tradeDate: '2020-12-01',
              },
            ],
          },
          summary: {
            cusip: '100',
            sortBy: undefined,
            longs: [
              {
                netObligationId: '',
                securityName: '',
                cusip: '',
                ticker: '',
                isin: '',
                netQuantity: 100,
                netTradeAmount: 200,
                settlementValue: 300,
                settlementDate: '',
                closePrice: 400,
                settlementStatus: '',
              },
            ],
            shorts: [
              {
                netObligationId: '',
                securityName: '',
                cusip: '',
                ticker: '',
                isin: '',
                netQuantity: 100,
                netTradeAmount: 200,
                settlementValue: 300,
                settlementDate: '',
                closePrice: 400,
                settlementStatus: '',
              },
            ],
            closed: [
              {
                netObligationId: '',
                securityName: '',
                cusip: '',
                ticker: '',
                isin: '',
                netQuantity: 100,
                netTradeAmount: 200,
                settlementValue: 300,
                settlementDate: '',
                closePrice: 400,
                settlementStatus: '',
              },
            ],
          },
          dialog: {
            cusip: false,
          },
        },
      },
    } as { dashboard: IDashboardState });
    expect(lastUpdated).toBeNull();
  });
});
