// import { IAdminState, IRouterState } from '../../types';
// import * as selectors from './admin.selectors';

// describe('AdminSelector', () => {
//   it('testing selectLastUpdated positions selector', () => {
//     const lastUpdated = selectors.selectLastUpdated({
//       router: {
//         state: {
//           root: {
//             params: {},
//             data: {},
//             url: [],
//             outlet: 'primary',
//             routeConfig: null,
//             queryParams: {},
//             firstChild: null,
//             children: [],
//           },
//           url: '/admin/cash',
//         },
//         navigationId: 6,
//       },
//       admin: {
//         netting: {
//           progress: false,
//           inProgressMessage: null,
//           schedule: {
//             scheduleType: 'Netting',
//             startTime: '7:00AM',
//             endTime: '11:00AM',
//             timezone: 'US/Hawaii',
//             hours: 4,
//             minutes: 30,
//             status: 'ACTIVE',
//           },
//           lastUpdated: new Date('2020-12-30T12:09:48.887Z'),
//           initialLoaded: null,
//           pageLoaded: null,
//           editing: false,
//           commitMessage: '',
//           commitError: '',
//           pageError: null,
//           pageSuccess: null,
//         },
//         security: {
//           progress: true,
//           inProgressMessage: null,
//           settlementDate: null,
//           schedule: {
//             scheduleType: 'SecuritiesSettlement',
//             startTime: '7:00PM',
//             endTime: '10:00PM',
//             timezone: 'IST',
//             hours: 0,
//             minutes: 0,
//             status: 'ACTIVE',
//           },
//           lastUpdated: new Date('2020-12-30T12:10:18.628Z'),
//           initialLoaded: null,
//           pageLoaded: null,
//           editing: false,
//           commitMessage: '',
//           commitError: '',
//           pageError: null,
//           pageSuccess: null,
//         },
//         cash: {
//           progress: true,
//           inProgressMessage: null,
//           settlementDate: null,
//           schedule: {
//             scheduleType: 'Cash',
//             startTime: '5:00AM',
//             endTime: '9:00PM',
//             timezone: 'US/Hawaii',
//             hours: 2,
//             minutes: 40,
//             status: 'ACTIVE',
//           },
//           lastUpdated: new Date('2020-12-30T12:09:40.592Z'),
//           initialLoaded: null,
//           pageLoaded: null,
//           editing: false,
//           commitMessage: '',
//           commitError: '',
//           pageError: null,
//           pageSuccess: null,
//         },
//       },
//     } as { admin: IAdminState });
//     expect(lastUpdated).toEqual(new Date('2020-12-30T12:09:40.592Z'));
//   });

//   it('testing selectLastUpdated obligations selector', () => {
//     const lastUpdated = selectors.selectLastUpdated({
//       router: {
//         state: {
//           root: {
//             params: {},
//             data: {},
//             url: [],
//             outlet: 'primary',
//             routeConfig: null,
//             queryParams: {},
//             firstChild: null,
//             children: [],
//           },
//           url: '/admin/netting',
//         },
//         navigationId: 6,
//       },
//       admin: {
//         netting: {
//           progress: false,
//           inProgressMessage: null,
//           schedule: {
//             scheduleType: 'Netting',
//             startTime: '7:00AM',
//             endTime: '11:00AM',
//             timezone: 'US/Hawaii',
//             hours: 4,
//             minutes: 30,
//             status: 'ACTIVE',
//           },
//           lastUpdated: new Date('2020-12-30T12:09:48.887Z'),
//           initialLoaded: null,
//           pageLoaded: null,
//           editing: false,
//           commitMessage: '',
//           commitError: '',
//           pageError: null,
//           pageSuccess: null,
//         },
//         security: {
//           progress: true,
//           inProgressMessage: null,
//           settlementDate: null,
//           schedule: {
//             scheduleType: 'SecuritiesSettlement',
//             startTime: '7:00PM',
//             endTime: '10:00PM',
//             timezone: 'IST',
//             hours: 0,
//             minutes: 0,
//             status: 'ACTIVE',
//           },
//           lastUpdated: new Date('2020-12-30T12:10:18.628Z'),
//           initialLoaded: null,
//           pageLoaded: null,
//           editing: false,
//           commitMessage: '',
//           commitError: '',
//           pageError: null,
//           pageSuccess: null,
//         },
//         cash: {
//           progress: true,
//           inProgressMessage: null,
//           settlementDate: null,
//           schedule: {
//             scheduleType: 'Cash',
//             startTime: '5:00AM',
//             endTime: '9:00PM',
//             timezone: 'US/Hawaii',
//             hours: 2,
//             minutes: 40,
//             status: 'ACTIVE',
//           },
//           lastUpdated: new Date('2020-12-30T12:09:40.592Z'),
//           initialLoaded: null,
//           pageLoaded: null,
//           editing: false,
//           commitMessage: '',
//           commitError: '',
//           pageError: null,
//           pageSuccess: null,
//         },
//       },
//     } as { admin: IAdminState });
//     expect(lastUpdated).toEqual(new Date('2020-12-30T12:09:48.887Z'));
//   });

//   // it('testing selectLastUpdated risk-mannagemet selector', () => {
//   //   const lastUpdated = selectors.selectLastUpdated({
//   //     router: {
//   //       state: {
//   //         root: {
//   //           params: {},
//   //           data: {},
//   //           url: [],
//   //           outlet: 'primary',
//   //           routeConfig: null,
//   //           queryParams: {},
//   //           firstChild: null,
//   //           children: [],
//   //         },
//   //         url: '/admin/security',
//   //       },
//   //       navigationId: 6,
//   //     },
//   //     admin: {
//   //       netting: {
//   //         progress: false,
//   //         inProgressMessage: null,
//   //         schedule: {
//   //           scheduleType: 'Netting',
//   //           startTime: '7:00AM',
//   //           endTime: '11:00AM',
//   //           timezone: 'US/Hawaii',
//   //           hours: 4,
//   //           minutes: 30,
//   //           status: 'ACTIVE',
//   //         },
//   //         lastUpdated: new Date('2020-12-30T12:09:48.887Z'),
//   //         initialLoaded: null,
//   //         pageLoaded: null,
//   //         editing: false,
//   //         commitMessage: '',
//   //         commitError: '',
//   //         pageError: null,
//   //         pageSuccess: null,
//   //       },
//   //       security: {
//   //         progress: true,
//   //         inProgressMessage: null,
//   //         settlementDate: null,
//   //         schedule: {
//   //           scheduleType: 'SecuritiesSettlement',
//   //           startTime: '7:00PM',
//   //           endTime: '10:00PM',
//   //           timezone: 'IST',
//   //           hours: 0,
//   //           minutes: 0,
//   //           status: 'ACTIVE',
//   //         },
//   //         lastUpdated: new Date('2020-12-30T12:10:18.628Z'),
//   //         initialLoaded: null,
//   //         pageLoaded: null,
//   //         editing: false,
//   //         commitMessage: '',
//   //         commitError: '',
//   //         pageError: null,
//   //         pageSuccess: null,
//   //       },
//   //       cash: {
//   //         progress: true,
//   //         inProgressMessage: null,
//   //         settlementDate: null,
//   //         schedule: {
//   //           scheduleType: 'Cash',
//   //           startTime: '5:00AM',
//   //           endTime: '9:00PM',
//   //           timezone: 'US/Hawaii',
//   //           hours: 2,
//   //           minutes: 40,
//   //           status: 'ACTIVE',
//   //         },
//   //         lastUpdated: new Date('2020-12-30T12:09:40.592Z'),
//   //         initialLoaded: null,
//   //         pageLoaded: null,
//   //         editing: false,
//   //         commitMessage: '',
//   //         commitError: '',
//   //         pageError: null,
//   //         pageSuccess: null,
//   //       },
//   //     },
//   //   } as { admin: IAdminState });
//   //   expect(lastUpdated).toEqual(new Date('2020-12-30T12:10:18.628Z'));
//   // });

//   it('testing selectLastUpdated none selector', () => {
//     const lastUpdated = selectors.selectLastUpdated({
//       router: {
//         state: {
//           root: {
//             params: {},
//             data: {},
//             url: [],
//             outlet: 'primary',
//             routeConfig: null,
//             queryParams: {},
//             firstChild: null,
//             children: [],
//           },
//           url: '/admin/none',
//         },
//         navigationId: 6,
//       },
//       admin: {
//         netting: {
//           progress: false,
//           inProgressMessage: null,
//           schedule: {
//             scheduleType: 'Netting',
//             startTime: '7:00AM',
//             endTime: '11:00AM',
//             timezone: 'US/Hawaii',
//             hours: 4,
//             minutes: 30,
//             status: 'ACTIVE',
//           },
//           lastUpdated: new Date('2020-12-30T12:09:48.887Z'),
//           initialLoaded: null,
//           pageLoaded: null,
//           editing: false,
//           commitMessage: '',
//           commitError: '',
//           pageError: null,
//           pageSuccess: null,
//         },
//         security: {
//           progress: true,
//           inProgressMessage: null,
//           settlementDate: null,
//           schedule: {
//             scheduleType: 'SecuritiesSettlement',
//             startTime: '7:00PM',
//             endTime: '10:00PM',
//             timezone: 'IST',
//             hours: 0,
//             minutes: 0,
//             status: 'ACTIVE',
//           },
//           lastUpdated: new Date('2020-12-30T12:10:18.628Z'),
//           initialLoaded: null,
//           pageLoaded: null,
//           editing: false,
//           commitMessage: '',
//           commitError: '',
//           pageError: null,
//           pageSuccess: null,
//         },
//         cash: {
//           progress: true,
//           inProgressMessage: null,
//           settlementDate: null,
//           schedule: {
//             scheduleType: 'Cash',
//             startTime: '5:00AM',
//             endTime: '9:00PM',
//             timezone: 'US/Hawaii',
//             hours: 2,
//             minutes: 40,
//             status: 'ACTIVE',
//           },
//           lastUpdated: new Date('2020-12-30T12:09:40.592Z'),
//           initialLoaded: null,
//           pageLoaded: null,
//           editing: false,
//           commitMessage: '',
//           commitError: '',
//           pageError: null,
//           pageSuccess: null,
//         },
//       },
//     } as { admin: IAdminState });
//     expect(lastUpdated).toBeNull();
//   });
// });
