apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-chart.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ionapp
    tier: {{ .Values.labels.tier }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  
